// Generated by CoffeeScript 1.3.1
(function() {
  var arr, hide, mousein, mouseout, resizePopup, show, startup;

  arr = ["Dies ist Content Nr 1 ", "Dies ist Content Nr 2 "];

  mousein = function() {
    return show(this);
  };

  mouseout = function() {
    return hide();
  };

  show = function(link) {
    var htmlcontent, id, newLeft, newTop;
    $(".popup").children().remove();
    id = $(link).attr("id");
    htmlcontent = arr[id];
    $(".popup").prepend(htmlcontent);
    $(".popup").show();
    newTop = $(link).offset().top - $(".popup").height() / 2 + 11;
    newLeft = $(link).offset().left - $(".popup").width() - 15;
    return $(".popup").offset({
      top: newTop,
      left: newLeft
    });
  };

  hide = function() {
    return $(".popup").hide();
  };

  resizePopup = function() {
    var newLeft, newTop;
    newTop = $(".active").offset().top - $(".popup").height() / 2 + 11;
    newLeft = $(".active").offset().left - $(".popup").width() - 15;
    return $(".popup").offset({
      top: newTop,
      left: newLeft
    });
  };

  startup = function() {
    $(".pops").mouseenter(mousein);
    $(".pops").mouseleave(mouseout);
    $(window).resize(resizePopup);
    return $(".popup").hide();
  };

  $(document).ready(startup);

}).call(this);
